add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_state$git_status$nodejs]($style)$character"

[character]
error_symbol = "\n[✗](bold cyan)"
success_symbol = "\n[❯](bold cyan)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol =" "
style = "italic purple"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style  = "blue"

[git_status]
format     = '([\[$all_status$ahead_behind\]]($style) )'
style      = 'cyan'
ahead      = '[⇡${count}](green)'
diverged   = '⇕⇡${ahead_count}⇣${behind_count}'
behind     = '⇣${count}'
conflicted = '[${count} ](red)'
up_to_date = '${count} '
untracked  = '[?${count} ](red)'
modified   = '!${count} '
staged     = '[+${count} ](yellow)'

